### ISSUE TITLE
Some missing files

### ISSUE THREAD

**Issue by BrixSat** [alexte/photo-booth#1]
Missing jquery folder and jquery.min.js

How do we make it take a photo? I see a bash script but nothing more....

Else great work.

**Comment by alexte** [comment]
jquery should be in node_modules/jquery/dist/ 

"npm install" should pull all needed dependencies, which includes jquery
I will add "npm install" to the README

The photo is actually taken with this command in "capture-photo.sh":

```
gphoto2 --capture-image-and-download --auto-detect \
        --filename images/orig/$filename >> /tmp/capture.log 2>&1

```

The script is started by the nodejs server using the joystick in the web GUI.

**Comment by alexte** [comment]
It was 2 weeks ago. I think I answered the question, and can close the issue.
